"""
Ontology seed for math concept extraction.

Labels use the pattern Domain:Subdomain:Concept for easy normalization.
You can extend or edit this list as you iterate on the pipeline.
"""

ONTOLOGY = [
    # Algebra
    "Algebra:Linear:Systems",
    "Algebra:Linear:Elimination",
    "Algebra:Linear:Substitution",
    "Algebra:Linear:Inequalities",
    "Algebra:Quadratic:Factoring",
    "Algebra:Quadratic:Discriminant",
    "Algebra:Quadratic:Vieta",
    "Algebra:Polynomials:RemainderTheorem",
    "Algebra:Polynomials:FactorTheorem",
    "Algebra:Polynomials:RootsMultiplicity",
    "Algebra:Polynomials:SymmetricPolynomials",
    "Algebra:Polynomials:AMGM",
    "Algebra:Polynomials:Jensen",
    "Algebra:Polynomials:FunctionalEquation",
    "Algebra:Rational:PartialFractions",
    "Algebra:Exponential:Properties",
    "Algebra:Logarithm:Properties",
    "Algebra:AbsoluteValue:Equations",
    "Algebra:Sequences:Arithmetic",
    "Algebra:Sequences:Geometric",
    "Algebra:Sequences:RecurrenceLinear",
    "Algebra:Series:Telescoping",
    "Algebra:Series:HarmonicManipulation",
    "Algebra:Inequalities:CauchySchwarz",
    "Algebra:Inequalities:AMGMHM",
    "Algebra:Inequalities:TriangleInequality",
    "Algebra:Complex:PolarForm",
    "Algebra:Complex:DeMoivre",
    "Algebra:Complex:RootsOfUnity",
    # Number theory
    "NT:Divisibility:GCDLCM",
    "NT:Divisibility:EuclideanAlgorithm",
    "NT:Divisibility:ModularArithmetic",
    "NT:Divisibility:CRT",
    "NT:Divisibility:LTE",
    "NT:Congruences:Linear",
    "NT:Congruences:Systems",
    "NT:Primes:Factorization",
    "NT:Primes:PrimeCounting",
    "NT:ArithmeticFunctions:Totient",
    "NT:ArithmeticFunctions:Mobius",
    "NT:Diophantine:Linear",
    "NT:Diophantine:Quadratic",
    "NT:Diophantine:Exponential",
    "NT:Diophantine:ChickenMcNugget",
    "NT:QuadraticResidues:LegendreSymbol",
    "NT:QuadraticResidues:QuadraticReciprocity",
    "NT:Orders:PrimitiveRoots",
    "NT:Orders:MultiplicativeOrder",
    "NT:CombinatorialNT:InclusionExclusion",
    "NT:CombinatorialNT:StarsBarsMod",
    "NT:Base:Representation",
    "NT:Parity:Arguments",
    # Combinatorics
    "Combo:Counting:RuleOfProduct",
    "Combo:Counting:Permutations",
    "Combo:Counting:Combinations",
    "Combo:Counting:BinomialTheorem",
    "Combo:Counting:Multinomial",
    "Combo:Counting:StarsAndBars",
    "Combo:Counting:InclusionExclusion",
    "Combo:Counting:Pigeonhole",
    "Combo:Counting:Recurrence",
    "Combo:Counting:GeneratingFunctions",
    "Combo:Counting:Burnside",
    "Combo:Probability:Conditional",
    "Combo:Probability:Bayes",
    "Combo:Probability:LinearityExpectation",
    "Combo:Probability:Variance",
    "Combo:Probability:MarkovChains",
    "Combo:Probability:RandomVariablesDiscrete",
    "Combo:Graphs:Basics",
    "Combo:Graphs:EulerPathCycle",
    "Combo:Graphs:Trees",
    "Combo:Graphs:Coloring",
    "Combo:Extremal:RamseyBasic",
    "Combo:Invariants:Parity",
    "Combo:Invariants:Monovariants",
    # Geometry
    "Geo:Triangles:CongruenceSimilarity",
    "Geo:Triangles:Area",
    "Geo:Triangles:CentroidIncenterCircumcenterOrthocenter",
    "Geo:Circles:PowerOfPoint",
    "Geo:Circles:ChordTangent",
    "Geo:Circles:InscribedCentralAngles",
    "Geo:Circles:ArcLengthSectorArea",
    "Geo:Polygons:Regular",
    "Geo:Polygons:AreaDecomposition",
    "Geo:Coordinates:DistanceSlopeMidpoint",
    "Geo:Coordinates:LineCircleIntersection",
    "Geo:Vectors:DotCross",
    "Geo:Vectors:AreaVolume",
    "Geo:Transformations:RotationReflection",
    "Geo:Transformations:DilationSimilarity",
    "Geo:3D:PlanesLines",
    "Geo:Trigonometry:LawOfSines",
    "Geo:Trigonometry:LawOfCosines",
    "Geo:Trigonometry:Identities",
    "Geo:Trigonometry:InverseTrig",
    "Geo:Trigonometry:TriangleHeightsMedians",
    "Geo:Analytic:Conics",
    "Geo:Optimization:GeometricInequalities",
    "Geo:Construction:CoordinateBash",
    # Calculus / Analysis
    "Calc:Limits:Algebraic",
    "Calc:Limits:LHopital",
    "Calc:Limits:SeriesExpansion",
    "Calc:Derivatives:Rules",
    "Calc:Derivatives:Optimization",
    "Calc:Derivatives:RelatedRates",
    "Calc:Integrals:Substitution",
    "Calc:Integrals:Parts",
    "Calc:Integrals:PartialFractions",
    "Calc:Integrals:Improper",
    "Calc:Series:ConvergenceTests",
    "Calc:Series:TaylorMaclaurin",
    "Calc:Series:PowerSeries",
    "Calc:DifferentialEq:FirstOrderLinear",
    "Calc:DifferentialEq:Separable",
    "Calc:Multivariable:Gradient",
    "Calc:Multivariable:MultipleIntegrals",
    "Calc:Multivariable:JacobianChangeOfVars",
    # Linear algebra
    "LA:Vectors:SpanBasis",
    "LA:Vectors:Orthogonality",
    "LA:Matrices:Determinant",
    "LA:Matrices:RankNullity",
    "LA:Matrices:Eigenvalues",
    "LA:Matrices:Diagonalization",
    "LA:Systems:GaussianElimination",
    "LA:InnerProduct:Projections",
    # General problem-solving
    "GPS:Substitution",
    "GPS:Casework",
    "GPS:Invariance",
    "GPS:ExtremalPrinciple",
    "GPS:Bounding",
    "GPS:Symmetry",
    "GPS:FunctionalEquation:Basic",
]


def ontology_as_text(prefix: str = "") -> str:
    """
    Return the ontology as a newline-joined string, optionally prefixed.
    Useful for embedding directly into prompts.
    """
    if prefix:
        return "\n".join(f"{prefix}{item}" for item in ONTOLOGY)
    return "\n".join(ONTOLOGY)
